[build]
  command = "npm install && npx eleventy"
  publish = "_site"


[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"


[[headers]]
 for = "/*"
 [headers.values]
   Access-Control-Allow-Origin = "*"