[build]
  command = "pm install && npm run build"
  publish = "_site"

 npm install && npm run build
 npm install && npm run build

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"


[[headers]]
 for = "/*"
 [headers.values]
   Access-Control-Allow-Origin = "*"