backend:
  name: github
  repo: msv69/la-roda

media_folder: "src/images/galleria"
public_folder: "/images/galleria"

collections:
  - name: "ciclisti"
    label: "Ciclisti"
    folder: "src/_data/ciclisti"
    create: true
    fields:
      - {label: "Nome", name: "nome", widget: "string"}
      - {label: "Foto", name: "foto", widget: "image"}
      - {label: "Palmares", name: "palmares", widget: "list"}


   
