backend:
  name: github
  repo: msv69/La-Roda

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "ciclisti"
    label: "Ciclisti"
    folder: "src/_data/ciclisti"
    create: true
    fields:
      - {label: "Nome", name: "nome", widget: "string"}
      - {label: "Cognome", name: "cognome", widget: "string"}
      - {label: "Foto", name: "foto", widget: "image"}
      - {label: "Biografia", name: "bio", widget: "text"}
      - {label: "Palmares", name: "palmares", widget: "list"}